[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Monitor speed
monitor_speed = 115200

; Flash and PSRAM memory settings for N16R8 (16MB Flash, 8MB OPI PSRAM)
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.arduino.partitions = default_16MB.csv

; Enable PSRAM support in code
build_flags = 
    -DBOARD_HAS_PSRAM
    ; Uncomment the line below if you are using the native USB port for Serial output
    ; -DARDUINO_USB_CDC_ON_BOOT=1

